apiVersion: apps/v1
kind: Deployment
metadata:
  name: taimespaceadmin-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: taimespaceadmin-ui
  template:
    metadata:
      labels:
        app: taimespaceadmin-ui
    spec:
      containers:
      - name: taimespaceadmin-ui
        image: taimespace.azurecr.io/taimespaceadmin:latest
        ports:
        - containerPort: 3000
        env:
        - name: RMQ_HOST
          value: rabbitmq
        - name: RMQ_PORT
          value: "5672"
        - name: RMQ_USER
          value: ${RABBITMQ_DEFAULT_USER}
        - name: RMQ_PASS
          value: ${RABBITMQ_DEFAULT_PASS}
        - name: RMQ_EXCHANGE_NAME
          value: TAIMESPACE_DEV
        - name: OPENAI_API_KEY
          value: ${OPENAI_API_KEY}
        - name: AUTH0_BASE_URL
          value: "http://98.67.208.13"
        - name: AUTH0_ISSUER_BASE_URL
          value: "https://dev-netzalist.eu.auth0.com"
        - name: AUTH0_AUDIENCE
          value: "https://dev-netzalist.eu.auth0.com/api/v2/"
        - name: AUTH0_CLIENT_ID
          value: ${AUTH0_CLIENT_ID}
        - name: AUTH0_CLIENT_SECRET
          value: ${AUTH0_CLIENT_SECRET}
        - name: AUTH0_SECRET
          value: ${AUTH0_SECRET}

---
apiVersion: v1
kind: Service
metadata:
  name: taimespaceadmin-ui
spec:
  type: LoadBalancer
  selector:
    app: taimespaceadmin-ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
